server:
  port: 8082

spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://postgres:5432/fullstack}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8081}

logging:
  level:
    root: INFO
    com.fullstack: DEBUG

